version: "3.7"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:7.2-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD:-admin} --save 20 1 --loglevel warning
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis:/data
    restart: unless-stopped

volumes:
  redis:
